### ISSUE TITLE
ufs read problems

### ISSUE THREAD

**Issue by Tkiliay** [B--B/android_device_xiaomi_sdm710-common#1]
The sequential read speed of grus on miui is 487.65MB/s and sequential read speed is around 130MB/s on pe+ (2023/7/19)

Tested more than twice with AndroBench

**Comment by B--B** [comment]
I've tested r/w multiple times in these days for other reasons and I cannot reproduce that behaviour, tested with CPDT, 1 Gb file size with caching and write buffering off, write speed is around 100 Mb/sec while read speed is around 250/300 Mb/sec with the max speed between 400/450 Mb/sec. But I must say that all the tests has been made with latest kernel, not the one in public build

**Comment by B--B** [comment]
Closing as I cannot reproduce the slow read speed behaviour with latest build/kernel
