### ISSUE TITLE
UFS reading speed problem

### ISSUE THREAD

**Issue by Tkiliay** [B--B/android_device_xiaomi_sdm710-common#2]
Written at the front I'm sorry for opening this same issue. However, there are still some problems with ufs.

Bug description：
Ufs is slow when copying files.
Using androbench to test, the reading result is 103.85MB/s

![Screenshot_20231005-220150_AndroBench](https://github.com/B--B/android_device_xiaomi_sdm710-common/assets/63190912/56ef3997-74b8-4b88-b9bd-dc2c4f1cc418) The screenshot is from the pe plus version you posted on xda, no third-party kernels and magisk modules are used. (PixelExperience_Plus_grus-13.0-20231005-1358-UNOFFICIAL) 

This is the result of testing on other roms （AlphaDroid-13.0-20231007-grus-vanilla-v1.10）

(https://sourceforge.net/projects/alphadroid-project/files/grus/AlphaDroid-13.0-20231007-grus-vanilla-v1.10.zip/download)）
![photo_2023-10-21_23-39-21](https://github.com/B--B/android_device_xiaomi_sdm710-common/assets/63190912/8a4bf712-25e7-4244-81e4-ed08ce18d1c4)

The kernel of this rom : https://github.com/elpaablo/kernel_xiaomi_grus
Alpha's Device tree : https://github.com/elpaablo/device_xiaomi_grus/tree/test-tree

**Comment by B--B** [comment]
I was still unable to reproduce such bad behaviour with my Grus on both A13/A14, but yes, performance are worse than AlphaDroid. It's not related to kernel at all, it's FBE the root cause: 680206bb55eb69ba469751daa286919fe0921b4d
After this write/read are more or less in line with that values. Another reason for high rw speed is readahead value, what's the size of readahead in AlphaDroid for Grus?

**Comment by Tkiliay** [comment]
> I was still unable to reproduce such bad behaviour with my Grus on both A13/A14, but yes, performance are worse than AlphaDroid. It's not related to kernel at all, it's FBE the root cause: [680206b](https://github.com/B--B/android_device_xiaomi_sdm710-common/commit/680206bb55eb69ba469751daa286919fe0921b4d) After this write/read are more or less in line with that values. Another reason for high rw speed is readahead value, what's the size of readahead in AlphaDroid for Grus?

He deleted the original device tree.  In his original device tree, the readahead value set by init.qcom.rc is 512KB.

**Comment by B--B** [comment]
In his test branch he set read_ahead to 1024 and noop as scheduler (that usually performs better than all other schedulers in benchmarks) for sda, and in his 14 branch read ahead does not seem to be configured so probably it's using ROM default value

https://github.com/elpaablo/device_xiaomi_grus/blob/test-tree/rootdir/etc/init.qcom.power.rc#L33

**Comment by Tkiliay** [comment]
How is the reading speed after switching to ICE encryption?

**Comment by B--B** [comment]
Seq read is around 450 MB/s, write near to 130 MB/s

**Comment by Tkiliay** [comment]
Looks like the problem is solved perfectly!  Thanks for your reply.
